<?php
/**
 * Created by PhpStorm.
 * User: yara
 * Date: 2017/7/28
 * Time: 15:17
 */
namespace Admini\Controller;


use Think\Model;

class AreaNewController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取区域类型列表
     * */
    public function index(){
        $this->CheckAuth();
        $article = M('area_new');
        $row_info = $article->where('1 = 1')->order('sort desc')->select();
//        $row = $this->genTree($row_info,'cate_id','parent_id','cate_name');
//        echo '<pre>';
//        var_dump($row_info);die();
        $this->assign('articleCateList',$row_info);
        $this->display();

    }

    /**
     * 删除区域类型
     * */
    public function delete(){
        if(!$this->CheckAuth(true,"Admini/AreaNew/delete")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
//        $this->myAjaxReturn(200,'删除成功!');die();
        if(empty($_POST['id'])){
            $this->myAjaxReturn(400,"非法操作！");
        }
        $id = I('post.id','','trim');
        $article = M('area_new');
        $row = $article->where('id = '.$id)->delete();
        if($row!==false){
            $log="{$_SESSION['admin']['account']}删除了区域类型[$id]";
            $this->writelog("area_new",$log);
            $this->myAjaxReturn(200,'删除成功!');
        }else{
            $this->myAjaxReturn(400,'删除失败!');
        }
    }

    /**
     * 添加
     * */
    public function add(){
        $this->CheckAuth();
        if(isset($_POST['submit'])){
            $draft = D('area_new');
            $row = $draft->addArticleCate();
            if($row['code'] == 200){
                $log = "{$_SESSION['admin']['account']}添加区域类型，ID为[{$row['id']}]";
                $this->writelog("area_new",$log);
                $this->success('添加成功!','index');
            }else{
                $this->error('添加失败!','add');
            }

        }else{
            $this->display();
        }
    }

    /**
     * 编辑
     * */
    public function update(){
        $this->CheckAuth();
        if(isset($_POST['submit'])){
            if(empty($_POST['id'])){
                $this->error('非法操作!','index');
            }
            $draft = D('area_new');
            $row = $draft->updateArticleCate();
            if($row['code'] == 200){
                $log = "{$_SESSION['admin']['account']}修改了区域类型，ID为[{$row['id']}]";
                $this->writelog("area_new",$log);
                $this->success('修改成功!','index');
            }else{
                $this->error('修改失败!','index');
            }

        }else{
            if(empty($_GET['id'])){
                $this->error('非法操作!','index');
            }
            $type = M('area_new');
            $info = $type->where('id = '.I('get.id','','trim'))->find();
            $this->assign('row_info',$info);
            $this->display();
        }
    }

}