<?php
/**
 * Created by PhpStorm.
 * User: yara
 * Date: 2017/7/11
 * Time: 09:27
 */
namespace Admini\Controller;


use Admini\Model\HouseInfoModel;
use Think\Model;

class HouseInfoController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 房屋列表
     * */
    public function index(){
        $this->CheckAuth();
        $areaNew = D('area_new');
        $areaNew_info = $areaNew->where('status = 1')->order('sort desc')->select();
        $this->assign('area_info',$areaNew_info);


        $this->display();
    }

    /**
     * 房屋列表ajax
     * */
    public function getHouseInfoAjax(){
        if(!$this->CheckAuth(true,"Admini/HouseInfo/index")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        $houseInfo = D('house_info');
        $row = $houseInfo->houseInfoListAjax();
        $this->myReturnAjax($row,'加载成功','暂无数据');
    }

    /**
     * 修改房屋状态
     * */
    public function updateStatus(){
        if(!$this->CheckAuth(true,"Admini/Article/updateStatus")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        $article = M('article');
        if($_POST['status'] === '1'){
            $data['closed'] = 0;
        }else if($_POST['status'] === '0'){
            $data['closed'] = 1;
        }else{
            die('非法操作!');
        }
        $row = $article->where('article_id = '.I('post.id','','trim'))->save($data);
        if($row !== false){
            $log = "{$_SESSION['admin']['account']}管理员修改了id为".I('post.id','','trim').'房屋';
            $this->writelog("member",$log);
            $this->myAjaxReturn(200,'修改成功！');
        }else{
            $this->myAjaxReturn(400,'修改失败!');
        }
    }

    /**
     * 删除房屋信息
     * */
    public function delete(){
        if(!$this->CheckAuth(true,"Admini/Article/delete")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        $article = M('house_info');
        $row = $article->where('id = '.I('post.id','','trim'))->delete();
        if($row !== false){
            $log = "{$_SESSION['admin']['account']}管理员删除了id为".I('post.id','','trim').'房屋信息';
            $this->writelog("member",$log);
            $this->myAjaxReturn(200,'删除成功！');
        }else{
            $this->myAjaxReturn(400,'删除失败!');
        }
    }

    /**
     * 添加房屋
     * */
    public function add(){
        $this->CheckAuth();
        if(isset($_POST['submit'])){
            $data = -1;
//            echo '<pre>';
//            var_dump($_POST['from']['img[']);die();

            $house_info = D('house_info');
            $row = $house_info->addHouseInfo($data);
            if($row['code'] == 200){
                $log = "{$_SESSION['admin']['account']}添加新房屋，ID为[{$row['id']}]";
                $this->writelog("article",$log);
                $this->myAjaxReturn(200,'添加成功!');
//                $this->success('添加成功!','articleList');
            }else if($row['code'] == 600){
                $this->myAjaxReturn(400,'图片上传失败!');
//                $this->error('图片上传失败!','add');
            }else{
                $this->myAjaxReturn(400,'添加失败!');
//                $this->error('添加失败!','add');
            }
        }else{
            $auth_article_cate = M('article_cate');
            $row_cate = $auth_article_cate->where('status = 1')->select();
            $this->assign('row_cate',$row_cate);
            $this->display();
        }
    }
    /**
     * 上传图片
     * */
    public function uploadImg(){
            if(!empty($_POST['key'])){
                $uploadUrl = "house/".$_POST['key'];
                $picurl = uploadOneImage($_FILES['file'],$uploadUrl);
                if($picurl[0]!=1){
                    $data = array('code'=>400,'msg'=>$picurl);
                }else{
                    $data = array('code'=>200,'src'=> $picurl[1]);
                }
                echo json_encode($data);die();
            }else{
                die('非法操作!');
            }
        }

    /**
     * 修改房屋
     * */
    public function updateHouseInfo(){
        $this->CheckAuth();
        if(isset($_POST['submit'])){
            if(empty($_POST['id'])){
                die('非法操作!');
            }
            $data = -1;
            /** @var HouseInfoModel  $house_info */
            $house_info = D('house_info');
            $row = $house_info->updateHouseInfo($data,I('post.id','','trim'));
            if($row['code'] == 200){
                $log = "{$_SESSION['admin']['account']}修改房屋，ID为[".I('post.id','','trim')."]";
                $this->writelog("house_info",$log);
                $this->myAjaxReturn(200,'修改成功!');
            }else{
                $this->myAjaxReturn(400,'修改失败!');
            }
        }else{
            if(empty($_POST['id'])){
                die('非法操作!');
            }else{
                $id = I('post.id','','trim');
            }
            //加载房源图册
            $house_photo = M('house_photo');
            $row['photo_list'] = $house_photo->where('status = 1 and house_id = '.$id)->order('sort desc')->select();
            $artice = M('house_info');
            $row['info'] = $artice->where('id = '.$id)->find();
            $row['info']['creat_house_time'] = date('Y-m-d',$row['info']['caeat_house_time']);
            if($row['info'] != false){
                $this->myAjaxReturn(200,'',$row);
            }else{
                $this->myAjaxReturn(400,'暂无数据!');
            }
        }
    }

    /**
     * 删除房源图片
     * */
    public function delImg(){
        if(!$this->CheckAuth(true,"Admini/HouseInfo/delImg")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        if(empty($_POST['id'])){
            $this->myAjaxReturn('400','非法操作!');
        }
        $house_photo = M('house_photo');
        $row = $house_photo->where('id = '.I('post.id','','trim'))->delete();
        if($row!==false){
            $this->myAjaxReturn(200,'删除成功!');
        }else{
            $this->myAjaxReturn(400,'删除失败!');
        }

    }

    /**
     *查看房屋图册
     * */
    public function lookImg(){
        if(!$this->CheckAuth(true,"Admini/HouseInfo/lookImg")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        if(empty($_POST['id'])){
            $this->myAjaxReturn(400,'非法操作!');
            die();
        }
        $house_img = M('house_photo');
        $row_list = $house_img->where('status = 1 and house_id = '.I('post.id','','trim'))->order('sort desc')->select();
        if($row_list!=false){
            $this->myAjaxReturn(200,'',$row_list);
        }else{
            $this->myAjaxReturn(400,'暂无数据!');
        }
    }

}