<?php
/**
 * Created by PhpStorm.
 * User: yara
 * Date: 2017/7/25
 * Time: 10:20
 */
namespace Admini\Controller;


use Think\Model;

class SystemArticleController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 系统新闻消息
     * */
    public function index(){
        $this->CheckAuth();
        $this->display();
    }

    /**
     * 获取系统新闻消息列表
     * */
    public function getListAjax(){
        if(!$this->CheckAuth(true,"Admini/SystemArticle/index")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        $loanlog = D('system_article');
        $row = $loanlog->getListAjax();
        $this->myReturnAjax($row,'','暂无数据!');
    }

    /**
     * 修改新闻状态
     * */
    public function updateStatus(){
        if(!$this->CheckAuth(true,"Admini/SystemArticle/updateStatus")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        $id = I('post.id','','trim');
        $data['status'] = I('post.status','','trim') == 1 ? 0 : 1;
        $admin = M('system_article');
        $row = $admin->where("id = {$id}")->save($data);
        if($row!==false){
            $log="{$_SESSION['admin']['account']}修改系统新闻[$id]的状态为{$data['status']}。";
            $this->writelog("system_article",$log);
            $this->myAjaxReturn(200,'修改成功!');
        }else{
            $this->myAjaxReturn(400,'修改失败!');
        }
    }

    /**
     * 添加系统新闻
     * */
    public function add(){
        $this->CheckAuth();
        if(isset($_POST['submit'])){
            $Loanlog = D('system_article');
            $row = $Loanlog->addSystemArticle();
            if($row != 400){
                $log = "{$_SESSION['admin']['account']}添加系统新闻，ID为[{$row}]";
                $this->writelog("system_article",$log);
                $this->success('添加成功!','index');
            }else{
                $this->error('添加失败!','add');
            }

        }else{
            $this->display();
        }
    }

    /**
     * 删除系统新闻
     * */
    public function delete(){
        if(!$this->CheckAuth(true,"Admini/SystemArticle/delete")){
            $this->myAjaxReturn(400,"没有使用该功能的权限！");
            die;
        }
        if(empty($_POST['id'])){
            die('非法操作!');
        }
        $id = I('post.id','','trim');
        $system_article = M('system_article');
        $row = $system_article->where('id = '.$id)->delete();
        if($row!==false){
            $log="{$_SESSION['admin']['account']}删除系统新闻[$id]。";
            $this->writelog("system_article",$log);
            $this->myAjaxReturn(200,'删除成功!');
        }else{
            $this->myAjaxReturn(400,'删除失败!');
        }
    }

    /**
     * 修改系统新闻
     * */
    public function update(){
        $this->CheckAuth();
        if(isset($_POST['submit'])){
            $systemArticle = D('system_article');
            $row = $systemArticle->updateSystem();
            if($row['code'] == 200){
                $log = "{$_SESSION['admin']['account']}修改了系统新闻，ID为[{$row['id']}]";
                $this->writelog("member",$log);
                $this->success('修改成功!','index');
            }else{
                $this->error('修改失败!','add');
            }

        }else{
            if(empty($_GET['id'])){
                die('非法操作！');
            }
            $systemArticle = M('system_article');
            $row_info = $systemArticle->where('id = '.I('get.id','','trim'))->find();
            $this->assign('info',$row_info);
            $this->display();
        }
    }

}